Improve exit code handling
jrstarke/aws-profile pull request #3
Opened 2018-10-11 19:20 UTC by grahamhar

When using aws-profile to run commands which return exit codes > 128 the
exit code is shifted to return just the first 8 bits (See the shells and
scripts section of https://en.wikipedia.org/wiki/Exit_status#Shell_and_scripts).
This is due to the use of os.WEXITSTATUS

Switching to use sys.exit causes the actual return code of the called
script to be returned. This was brought to light when attempting to use
the awscli and the return code was 255, but the aws-profile returned
zero. This resulted in incorrect control flow in the wrapping script.

2018-10-23 08:54 UTC, grahamhar commented
@jrstarke Is this still maintained? As you publish this on pypi could I be added as a maintainer if that helps?

2018-10-24 05:06 UTC, jrstarke commented
My appologies @grahamhar, somehow I missed the initial message. Looking at this now

2018-10-24 05:25 UTC, jrstarke requested changes

2018-10-24 05:25 UTC, jrstarke commented on awsprofile/__init__.py
> +    exit(sys.exit(returncode))
Tested this out, and it works as expected

2018-10-24 05:25 UTC, jrstarke commented on setup.py
> +    'awscli>=1.16.31',
```suggestion
```

I can understand why having the awscli would be convenient, but I know a number of people that install it though different means, like homebrew, and this could potentially cause issues for them and their existing workflows.

As a further note, I tested this change under the `aws-cli/1.15.84` and it worked fine.

2018-10-24 05:30 UTC, jrstarke commented
Looks good overall. Tested it out with `aws-profile <profile> python -c "import sys; sys.exit(255)"` and `aws-profile <profile> python -c "import sys; sys.exit(100)"`. `echo $?` showed the expected exit code.

One small change requested, because this doesn't actually require the AWS CLI, and works well with any tools that use the AWS SDK for a number of languages without needing the AWS CLI.

2018-10-24 06:29 UTC, grahamhar commented on awsprofile/__init__.py
> +    exit(sys.exit(returncode))
awscli is used:

from awscli.utils import json_encoder
from awscli.customizations.assumerole import JSONFileCache

I added this as I did all my work in a clean virtualenv and exceptions for no such module were thrown. Happy to strip this out if you still want but anyone using this in a clean python environment will be unable to use it without a manual install of the awscli package.

2018-10-24 06:31 UTC, grahamhar commented on setup.py
> +    'awscli>=1.16.31',
wscli is used:

from awscli.utils import json_encoder
from awscli.customizations.assumerole import JSONFileCache

I added this as I did all my work in a clean virtualenv and exceptions for no such module were thrown. Happy to strip this out if you still want but anyone using this in a clean python environment will be unable to use it without a manual install of the awscli package.

2018-10-24 06:37 UTC, grahamhar commented
On a separate note would you be open to a PR adding some unit tests?

2018-10-24 06:39 UTC, grahamhar commented on setup.py
> +    'awscli>=1.16.31',
As this is a separate issue maybe I should pull it into a separate PR anyway?

2018-10-24 14:27 UTC, jrstarke commented
I'd be totally open to a unit testing PR.

2018-10-24 14:33 UTC, jrstarke commented on setup.py
> +    'awscli>=1.16.31',
Yeah, I totally understand that is how you originally exercised the issue, but it seems like the simplest verification test is the one that I performed https://github.com/jrstarke/aws-profile/pull/3#issuecomment-432518076.

It's important to remember that this tool is fairly command agnostic, and that at the end of the day, the issue you mentioned is that you ran a command through aws-profile, that command exited 255, but aws-profile didn't pass it though. In your specific case, it was the aws cli, but that's not really required to get the simplest reproduction.

I've also seen a pattern where, using requirements files, you have a split requirements file: Those things that are really required just to run the thing, and those that are used during development. In this case however, I'm still not convinced that the AWS CLI would fall into either.

2018-10-24 21:23 UTC, grahamhar commented on setup.py
> +    'awscli>=1.16.31',
I’ll pull out the dependency part of this into a separate PR as I feel it is important but I don’t think I am putting the point across on it correctly and I don’t want to distract from the main fix I need under this PR which is the exit code handling. I’m on phone at moment so will update first thing tomorrow

2018-10-25 09:01 UTC, grahamhar commented
@jrstarke I've removed the awscli dependancy. expect a PR for unit testing soon :)

2018-10-25 13:58 UTC, jrstarke approved these changes

2018-10-25 13:58 UTC, merged

2018-10-25 14:00 UTC, grahamhar commented
Thank you

2018-10-25 14:06 UTC, jrstarke commented
Thanks for putting the work in on this. This has been released in v0.4.0

2018-10-26 04:07 UTC, jrstarke commented
My apologies, I just installed in a completely fresh environment, and I was wrong on awscli being a dependency :(